Repository axibase/atsd-use-cases, pull requests merged in 2018-06, with the labels that each got.

#273 [Dev] cadvisor guidde
  how-to/README.md
  how-to/cadvisor/README.md
  how-to/cadvisor/images/container_disk_detail_portal.png
  how-to/cadvisor/images/container_overview_portal.png
  how-to/cadvisor/images/docker_distributed.png
  how-to/cadvisor/images/docker_host_portal.png
  how-to/cadvisor/images/docker_multi_host_portal.png
Labels: pending

#272 technical-writing-seminar-redux
  .dictionary
  tutorials/workshop/images/bad-tech.png
  tutorials/workshop/images/good-tech.png
  tutorials/workshop/images/rails-img.png
  tutorials/workshop/technical-writing.md
Labels: done

#257 Support #5298: How-to: subtract data for subsequent values
  .dictionary
  README.md
  tutorials/README.md
  tutorials/subtract-subsequent-values/README.md
  tutorials/subtract-subsequent-values/images/button.png
  tutorials/subtract-subsequent-values/images/dc07-delta1.png
  tutorials/subtract-subsequent-values/images/dc07-raw.png
  tutorials/subtract-subsequent-values/images/dc07.png
Labels: done

#267 PR Report Refactor
  integrations/github/images/add-new-email.png
  integrations/github/images/search-rule.png
  integrations/github/pr-report.md
  integrations/github/resources/github-daily-pr-status.xml
  integrations/github/resources/graphql-queries.xml
Labels: done

#280 Link repair
  .dictionary
  integrations/activemq/README.md
  integrations/aws/cloud-watch-alert/README.md
  integrations/aws/route53-health-checks/README.md
  integrations/aws/route53-health-checks/uptime-report.md
  integrations/cadvisor/README.md
  integrations/docker/README.md
  integrations/docker/docker-engine.md
  integrations/github/fork-notification.md
  integrations/github/issue-notification.md
  integrations/github/pr-notification.md
  integrations/github/pr-report.md
  integrations/github/project-release-notification.md
  integrations/github/push-notification.md
  integrations/github/troubleshooting.md
  integrations/github/watch-notification.md
  integrations/itm/README.md
  integrations/itm/resources/hd.ini
  integrations/itm/resources/inotify_sender.sh
  integrations/itm/resources/metric-list.md
  integrations/kafka/README.md
  integrations/kafka/brokers-monitoring/README.md
  integrations/marathon/capacity-and-usage/README.md
  integrations/marathon/capacity-and-usage/manual-upload.md
  integrations/socrata/iowa-compensation/README.md
  integrations/socrata/python/README.md
  integrations/socrata/python/resources/docker-compose.yml
  integrations/zookeeper/README.md
  research/baltimore-pd/README.md
  research/chicago-crime-stats/README.md
  research/fitness-index/README.md
  research/hawaii-prices/README.md
  research/uk-aviation/README.md
  research/us-mortality/README.md
  research/us-mortality/resources/city-size.txt
  research/us-mortality/resources/us-regions.txt
  tutorials/add-calculated-value/README.md
  tutorials/calculated-values/README.md
  tutorials/historize/README.md
  tutorials/moving-avg/README.md
  tutorials/schema-based-parser-mod/README.md
  tutorials/workshop/lets-encrypt.md
  tutorials/workshop/technical-writing.md
  tutorials/workshop/webgl.md
Labels: done

#285 minor-refactor
  .dictionary
  tutorials/workshop/technical-writing.md
Labels: done, question

#289 time-series-database
  .dictionary
  tutorials/README.md
  tutorials/time-series-database/README.md
  tutorials/time-series-database/images/energinet_detailed.png
  tutorials/time-series-database/images/energinet_report.png
Labels: done

#291 data-flow-control
  .dictionary
  tutorials/README.md
  tutorials/data-flow-control/README.md
  tutorials/data-flow-control/images/block.png
  tutorials/data-flow-control/images/discard_mode.png
  tutorials/data-flow-control/images/monitor.png
  tutorials/data-flow-control/images/rule1.png
Labels: done

#293 allocating-resources
  .dictionary
  tutorials/README.md
  tutorials/allocating-resources/README.md
  tutorials/allocating-resources/images/real-time-insights.png
Labels: done

#294 docker-monitoring
  .dictionary
  tutorials/README.md
  tutorials/docker-monitoring/README.md
  tutorials/docker-monitoring/images/api_service_portal_atsd1.png
  tutorials/docker-monitoring/images/basic_arch2.png
  tutorials/docker-monitoring/images/distributed_arch.png
  tutorials/docker-monitoring/images/docker_container_engine_logo.png
  tutorials/docker-monitoring/images/docker_introduction.vsd_.png
  tutorials/docker-monitoring/images/microservices_docker2.png
Labels: done

#295 data-forecasting
  .dictionary
  .vuepress/config.js
  chart-of-the-day/2015.md
  chart-of-the-day/README.md
  chart-of-the-day/duck-duck-go/README.md
  chart-of-the-day/duck-duck-go/images/button.png
  chart-of-the-day/duck-duck-go/images/portal_ddg_final.png
Labels: done

#290 composite-intervals
  .dictionary
  tutorials/README.md
  tutorials/composite-intervals/README.md
  tutorials/composite-intervals/images/composite-query-settings.png
  tutorials/composite-intervals/images/composite_interval_query.png
  tutorials/composite-intervals/images/composite_interval_query_widget.png
  tutorials/composite-intervals/images/itm-history-collection-settings.png
Labels: done

#283 [Dev] cAdvisor improvments
  .dictionary
  integrations/cadvisor/README.md
  integrations/cadvisor/cadvisor-atsd-http.md
  integrations/cadvisor/docker-compose.yml
  integrations/cadvisor/images/button.png
Labels: done

#299 700 seconds
  .dictionary
  chart-of-the-day/2015.md
  chart-of-the-day/700-seconds/README.md
  chart-of-the-day/700-seconds/images/admin-ajax.png
  chart-of-the-day/700-seconds/images/aws_cpu_credits_t2.png
  chart-of-the-day/700-seconds/images/button.png
  chart-of-the-day/README.md
Labels: done

#297 environmental-monitoring
  .dictionary
  tutorials/README.md
  tutorials/environmental-monitoring/README.md
  tutorials/environmental-monitoring/images/atsd_forecast_settings.png
  tutorials/environmental-monitoring/images/atsd_forecast_vs_actual.png
  tutorials/environmental-monitoring/images/atsd_metrics1.png
  tutorials/environmental-monitoring/images/button.png
  tutorials/environmental-monitoring/images/china_air_quality.png
  tutorials/environmental-monitoring/images/collector_file_job.png
  tutorials/environmental-monitoring/images/collector_parser1.png
  tutorials/environmental-monitoring/images/correlation.png
  tutorials/environmental-monitoring/images/eigenvectors.png
  tutorials/environmental-monitoring/images/forecast.png
  tutorials/environmental-monitoring/images/insertion_delay.png
  tutorials/environmental-monitoring/images/pairs.png
  tutorials/environmental-monitoring/images/portal_air_quality1.png
  tutorials/environmental-monitoring/images/sing_vals.png
  tutorials/environmental-monitoring/images/standard_deviation.png
  tutorials/environmental-monitoring/images/total_delay1.png
Labels: done

#300 combining-windows
  .dictionary
  chart-of-the-day/2015.md
  chart-of-the-day/README.md
  tutorials/README.md
  tutorials/combining-windows/README.md
  tutorials/combining-windows/images/button.png
  tutorials/combining-windows/images/chartlab.png
  tutorials/combining-windows/images/trading-view.png
Labels: done
